<?php

require_once 'libs/Foo.php';

/**
 * Test class for Foo.
 * Generated by PHPUnit on 2011-10-28 at 14:43:19.
 */
class FooTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Foo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Foo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testBar().
     */
    public function testBar()
    {
    	$this->assertEquals(42, $this->object->bar());
    }
}
?>
