<?php
namespace Core;

if(!class_exists("\\Core\\Mock") && !class_exists("\\Core\\Mock2") && !class_exists("\\Core\\Mock3")) {
    class Mock {
        public $param1;
        public $param2;
        public $param3;
    }

    class Mock2 extends Mock {
        public function __construct($param1, $param2, $param3) {
            $this->param1 = $param1;
            $this->param2 = $param2;
            $this->param3 = $param3;
        }
    }

    class Mock3 extends Mock2 {}
}

require_once 'C:\Users\Galuh Utama\workspace\Core\vendors\Core\ServiceContainer.php';

/**
 * Test class for ServiceContainer.
 * Generated by PHPUnit on 2012-02-17 at 05:51:32.
 */
class ServiceContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ServiceContainer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ServiceContainer;
        $this->object->register("\\Core\\Mock", array(), "Mock");
        $this->object->register("\\Core\\Mock2", array(
            "param1" => "value1",
            "param2" => "value2",
            "param3" => "value3"
        ), "Mock2");
        $this->object->register("\\Core\\Mock3", array(
            "param1" => "foo",
            "param2" => "bar",
            "param3" => array(1,2,3)
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testHasService()
    {
        $this->assertTrue($this->object->hasService("Mock"));
        $this->assertTrue($this->object->hasService("Mock2"));
        $this->assertTrue($this->object->hasService("\\Core\\Mock3"));
        $this->assertFalse($this->object->hasService("Mock4"));
        $this->assertFalse($this->object->hasService("Inexists"));
    }

    public function testGetService()
    {
        $this->assertTrue($this->object->getService("Mock") instanceof Mock);
        $this->assertTrue($this->object->getService("Mock2") instanceof Mock2);
        $this->assertTrue($this->object->getService("\\Core\\Mock3") instanceof Mock3);
    }

    /**
     * @expectedException \Core\ServiceNotAvailableException
     */
    public function testGetService2()
    {
        $this->object->getService("Inexists");
    }


    public function testRegister()
    {
        $this->object->clear();
        $this->assertEquals(0, $this->object->count());

        $this->object->register("\\Core\\Mock", array(), "Mock");
        $this->object->register("\\Core\\Mock2", array(
            "param1" => "value1",
            "param2" => "value2",
            "param3" => "value3"
        ), "Mock2");
        $this->object->register("\\Core\\Mock3", array(
            "param1" => "foo",
            "param2" => "bar",
            "param3" => array(1,2,3)
        ), "Mock3");
        $this->assertEquals(3, $this->object->count());

        // service name must not be null
        $this->object->register(null);
        $this->assertEquals(3, $this->object->count());

        $this->object->register("\\Core\\Mock4", array(), "Mock4");
        $this->assertEquals(4, $this->object->count());

        // same registered service
        $this->object->register("\\Core\\Mock", array(), "Mock");
        $this->assertEquals(4, $this->object->count());
    }


    public function test__get()
    {
        $this->assertTrue($this->object->Mock instanceof Mock);
        $this->assertTrue($this->object->Mock2 instanceof Mock2);
    }


    public function test__call()
    {
        $this->assertTrue($this->object->getMockService() instanceof Mock);
        $this->assertTrue($this->object->getMock2Service() instanceof Mock2);
    }


    public function testIterator()
    {
        foreach($this->object as $service) {
            $this->assertNotNull($service->getName());
        }
    }
}
?>
