<?php

require_once 'C:\Users\Galuh Utama\workspace\Core\libs\Core\Core_Inflector.php';

/**
 * Test class for RouteParser.
 * Generated by PHPUnit on 2012-01-28 at 14:32:16.
 */
class Core_InflectorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Core_InflectorTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        Core_Inflector::reset();
    }


    public function testPluralize2()
    {
        $this->assertEquals("women", Core_Inflector::pluralize("woman"));
        $this->assertEquals("children", Core_Inflector::pluralize("child"));
        $this->assertEquals("people", Core_Inflector::pluralize("person"));

        $this->assertEquals("kisses", Core_Inflector::pluralize("kiss"));
        $this->assertEquals("phases", Core_Inflector::pluralize("phase"));
        $this->assertEquals("dishes", Core_Inflector::pluralize("dish"));
        $this->assertEquals("massages", Core_Inflector::pluralize("massage"));
        $this->assertEquals("witches", Core_Inflector::pluralize("witch"));
        $this->assertEquals("judges", Core_Inflector::pluralize("judge"));

        $this->assertEquals("tests", Core_Inflector::pluralize("test"));
        $this->assertEquals("laps", Core_Inflector::pluralize("lap"));
        $this->assertEquals("cats", Core_Inflector::pluralize("cat"));
        $this->assertEquals("clocks", Core_Inflector::pluralize("clock"));
        $this->assertEquals("cuffs", Core_Inflector::pluralize("cuff"));
        $this->assertEquals("deaths", Core_Inflector::pluralize("death"));

        $this->assertEquals("boys", Core_Inflector::pluralize("boy"));
        $this->assertEquals("girls", Core_Inflector::pluralize("girl"));
        $this->assertEquals("chairs", Core_Inflector::pluralize("chair"));

        $this->assertEquals("heroes", Core_Inflector::pluralize("hero"));
        $this->assertEquals("potatoes", Core_Inflector::pluralize("potato"));
        $this->assertEquals("volcanoes", Core_Inflector::pluralize("volcano"));

        $this->assertEquals("cherries", Core_Inflector::pluralize("cherry"));
        $this->assertEquals("ladies", Core_Inflector::pluralize("lady"));

        $this->assertEquals("days", Core_Inflector::pluralize("day"));
        $this->assertEquals("monkeys", Core_Inflector::pluralize("monkey"));
    }

    // From here on, tests are taken from Lithium.

    /**
     * Tests singularization inflection rules
     *
     * @return void
     */
    public function testSingularize() {
        $this->assertEquals(Core_Inflector::singularize('categorias'), 'categoria');
        $this->assertEquals(Core_Inflector::singularize('menus'), 'menu');
        $this->assertEquals(Core_Inflector::singularize('news'), 'news');
        $this->assertEquals(Core_Inflector::singularize('food_menus'), 'food_menu');
        $this->assertEquals(Core_Inflector::singularize('Menus'), 'Menu');
        $this->assertEquals(Core_Inflector::singularize('FoodMenus'), 'FoodMenu');
        $this->assertEquals(Core_Inflector::singularize('houses'), 'house');
        $this->assertEquals(Core_Inflector::singularize('powerhouses'), 'powerhouse');
        $this->assertEquals(Core_Inflector::singularize('quizzes'), 'quiz');
        $this->assertEquals(Core_Inflector::singularize('Buses'), 'Bus');
        $this->assertEquals(Core_Inflector::singularize('buses'), 'bus');
        $this->assertEquals(Core_Inflector::singularize('matrix_rows'), 'matrix_row');
        $this->assertEquals(Core_Inflector::singularize('matrices'), 'matrix');
        $this->assertEquals(Core_Inflector::singularize('vertices'), 'vertex');
        $this->assertEquals(Core_Inflector::singularize('indices'), 'index');
        $this->assertEquals(Core_Inflector::singularize('Aliases'), 'Alias');
        $this->assertEquals(Core_Inflector::singularize('Alias'), 'Alias');
        $this->assertEquals(Core_Inflector::singularize('Media'), 'Media');
        $this->assertEquals(Core_Inflector::singularize('alumni'), 'alumnus');
        $this->assertEquals(Core_Inflector::singularize('bacilli'), 'bacillus');
        $this->assertEquals(Core_Inflector::singularize('cacti'), 'cactus');
        $this->assertEquals(Core_Inflector::singularize('foci'), 'focus');
        $this->assertEquals(Core_Inflector::singularize('fungi'), 'fungus');
        $this->assertEquals(Core_Inflector::singularize('nuclei'), 'nucleus');
        $this->assertEquals(Core_Inflector::singularize('octopuses'), 'octopus');
        $this->assertEquals(Core_Inflector::singularize('radii'), 'radius');
        $this->assertEquals(Core_Inflector::singularize('stimuli'), 'stimulus');
        $this->assertEquals(Core_Inflector::singularize('syllabi'), 'syllabus');
        $this->assertEquals(Core_Inflector::singularize('termini'), 'terminus');
        $this->assertEquals(Core_Inflector::singularize('viri'), 'virus');
        $this->assertEquals(Core_Inflector::singularize('people'), 'person');
        $this->assertEquals(Core_Inflector::singularize('gloves'), 'glove');
        $this->assertEquals(Core_Inflector::singularize('doves'), 'dove');
        $this->assertEquals(Core_Inflector::singularize('lives'), 'life');
        $this->assertEquals(Core_Inflector::singularize('knives'), 'knife');
        $this->assertEquals(Core_Inflector::singularize('wolves'), 'wolf');
        $this->assertEquals(Core_Inflector::singularize('shelves'), 'shelf');
        $this->assertEquals(Core_Inflector::singularize(''), '');
    }

    /**
     * Tests pluralization inflection rules
     *
     * @return void
     */
    public function testPluralize() {
        $this->assertEquals(Core_Inflector::pluralize('categoria'), 'categorias');
        $this->assertEquals(Core_Inflector::pluralize('house'), 'houses');
        $this->assertEquals(Core_Inflector::pluralize('powerhouse'), 'powerhouses');
        $this->assertEquals(Core_Inflector::pluralize('Bus'), 'Buses');
        $this->assertEquals(Core_Inflector::pluralize('bus'), 'buses');
        $this->assertEquals(Core_Inflector::pluralize('menu'), 'menus');
        $this->assertEquals(Core_Inflector::pluralize('news'), 'news');
        $this->assertEquals(Core_Inflector::pluralize('food_menu'), 'food_menus');
        $this->assertEquals(Core_Inflector::pluralize('Menu'), 'Menus');
        $this->assertEquals(Core_Inflector::pluralize('FoodMenu'), 'FoodMenus');
        $this->assertEquals(Core_Inflector::pluralize('quiz'), 'quizzes');
        $this->assertEquals(Core_Inflector::pluralize('matrix_row'), 'matrix_rows');
        $this->assertEquals(Core_Inflector::pluralize('matrix'), 'matrices');
        $this->assertEquals(Core_Inflector::pluralize('vertex'), 'vertices');
        $this->assertEquals(Core_Inflector::pluralize('index'), 'indices');
        $this->assertEquals(Core_Inflector::pluralize('Alias'), 'Aliases');
        $this->assertEquals(Core_Inflector::pluralize('Aliases'), 'Aliases');
        $this->assertEquals(Core_Inflector::pluralize('Media'), 'Media');
        $this->assertEquals(Core_Inflector::pluralize('alumnus'), 'alumni');
        $this->assertEquals(Core_Inflector::pluralize('bacillus'), 'bacilli');
        $this->assertEquals(Core_Inflector::pluralize('cactus'), 'cacti');
        $this->assertEquals(Core_Inflector::pluralize('focus'), 'foci');
        $this->assertEquals(Core_Inflector::pluralize('fungus'), 'fungi');
        $this->assertEquals(Core_Inflector::pluralize('nucleus'), 'nuclei');
        $this->assertEquals(Core_Inflector::pluralize('octopus'), 'octopuses');
        $this->assertEquals(Core_Inflector::pluralize('radius'), 'radii');
        $this->assertEquals(Core_Inflector::pluralize('stimulus'), 'stimuli');
        $this->assertEquals(Core_Inflector::pluralize('syllabus'), 'syllabi');
        $this->assertEquals(Core_Inflector::pluralize('terminus'), 'termini');
        $this->assertEquals(Core_Inflector::pluralize('virus'), 'viri');
        $this->assertEquals(Core_Inflector::pluralize('person'), 'people');
        $this->assertEquals(Core_Inflector::pluralize('people'), 'people');
        $this->assertEquals(Core_Inflector::pluralize('glove'), 'gloves');
        $this->assertEquals(Core_Inflector::pluralize(''), '');

        $result = Core_Inflector::pluralize('errata');
        $this->assertNull(Core_Inflector::rules('plural', array('/rata/' => '\1ratum')));
        $this->assertEquals(Core_Inflector::pluralize('errata'), $result);

        Core_Inflector::reset();
        $this->assertNotEquals(Core_Inflector::pluralize('errata'), $result);
    }

    /**
     * testInflectorSlug method
     *
     * @return void
     */
    public function testSlug() {
        $result = Core_Inflector::slug('Foo Bar: Not just for breakfast any-more');
        $expected = 'Foo-Bar-Not-just-for-breakfast-any-more';
        $this->assertEquals($expected, $result);

        $result = Core_Inflector::slug('Foo Bar: Not just for breakfast any-more', '_');
        $expected = 'Foo_Bar_Not_just_for_breakfast_any_more';
        $this->assertEquals($expected, $result);

        $result = Core_Inflector::slug('this/is/a/path', '_');
        $expected = 'this_is_a_path';
        $this->assertEquals($expected, $result);

        $result = Core_Inflector::slug('Foo Bar: Not just for breakfast any-more', "+");
        $expected = 'Foo+Bar+Not+just+for+breakfast+any+more';
        $this->assertEquals($expected, $result);

        $result = Core_Inflector::slug('Äpfel Über Öl grün ärgert groß öko');
        $expected = 'Aepfel-Ueber-Oel-gruen-aergert-gross-oeko';
        $this->assertEquals($expected, $result);

        $result = Core_Inflector::slug('The truth - and- more- news');
        $expected = 'The-truth-and-more-news';
        $this->assertEquals($expected, $result);

        $result = Core_Inflector::slug('The truth: and more news');
        $expected = 'The-truth-and-more-news';
        $this->assertEquals($expected, $result);

        $message = 'La langue française est un attribut de souveraineté en France';
        $result = Core_Inflector::slug($message, '-');
        $expected = 'La-langue-francaise-est-un-attribut-de-souverainete-en-France';
        $this->assertEquals($expected, $result);

        $result = Core_Inflector::slug('!@$#exciting stuff! - what !@-# was that?');
        $expected = 'exciting-stuff-what-was-that';
        $this->assertEquals($expected, $result);

        $result = Core_Inflector::slug('20% of profits went to me!');
        $expected = '20-of-profits-went-to-me';
        $this->assertEquals($expected, $result);

        $result = Core_Inflector::slug('#this melts your face1#2#3');
        $expected = 'this-melts-your-face1-2-3';
        $this->assertEquals($expected, $result);

        $result = Core_Inflector::slug('ThisMeltsYourFace');
        $expected = 'This-Melts-Your-Face';
        $this->assertEquals($expected, $result);
    }

    public function testAddingInvalidRules() {
        $before = array(
            Core_Inflector::rules('singular'),
            Core_Inflector::rules('plural'),
            Core_Inflector::rules('transliteration')
        );
        $this->assertNull(Core_Inflector::rules('foo'));
        $this->assertEquals($before, array(
            Core_Inflector::rules('singular'),
            Core_Inflector::rules('plural'),
            Core_Inflector::rules('transliteration')
        ));
    }

    public function testAddingSingularizationRules() {
        $before = Core_Inflector::rules('singular');
        $result = Core_Inflector::singularize('errata');
        $this->assertNull(Core_Inflector::rules('singular', array('/rata/' => '\1ratus')));
        $this->assertEquals(Core_Inflector::singularize('errata'), $result);

        Core_Inflector::reset();
        $this->assertNotEquals(Core_Inflector::singularize('errata'), $result);

        $after = Core_Inflector::rules('singular');
        $expected = array(
            'rules', 'irregular', 'uninflected', 'regexUninflected', 'regexIrregular'
        );
        $this->assertEquals(array_keys($before), $expected);
        $this->assertEquals(array_keys($after), $expected);

        $result = array_diff($after['rules'], $before['rules']);
        $this->assertEquals($result, array('/rata/' => '\1ratus'));

        foreach (array('irregular', 'uninflected', 'regexUninflected', 'regexIrregular') as $key) {
            $this->assertEquals($before[$key], $after[$key]);
        }

        $this->assertNull(Core_Inflector::rules('singular', array('rules' => array(
            '/rata/' => '\1ratus'
        ))));
        $this->assertEquals(Core_Inflector::rules('singular'), $after);
    }

    /**
     * Tests that rules for uninflected singular words are kept in sync with the plural, and vice
     * versa.
     *
     * @return void
     */
    public function testIrregularWords() {
        $expectedPlural = Core_Inflector::rules('plural');
        $this->assertFalse(isset($expectedPlural['irregular']['bar']));

        $expectedSingular = Core_Inflector::rules('singular');
        $this->assertFalse(isset($expectedSingular['irregular']['foo']));

        Core_Inflector::rules('singular', array('irregular' => array('foo' => 'bar')));

        $resultSingular = Core_Inflector::rules('singular');
        $this->assertEquals($resultSingular['irregular']['foo'], 'bar');
        unset($resultSingular['irregular']['foo']);

        $this->assertEquals($resultSingular, $expectedSingular);

        $resultPlural = Core_Inflector::rules('plural');
        $this->assertEquals($resultPlural['irregular']['bar'], 'foo');
        unset($resultPlural['irregular']['bar']);

        $this->assertEquals($resultPlural, $expectedPlural);
    }

    /**
     * testVariableNaming method
     *
     * @return void
     */
    public function testCamelize() {
        $this->assertEquals(Core_Inflector::camelize('test-field'), 'TestField');
        $this->assertEquals(Core_Inflector::camelize('test_field'), 'TestField');
        $this->assertEquals(Core_Inflector::camelize('test_fieLd', false), 'testFieLd');
        $this->assertEquals(Core_Inflector::camelize('test field', false), 'testField');
        $this->assertEquals(Core_Inflector::camelize('Test_field', false), 'testField');
    }

    /**
     * testClassNaming method
     *
     * @return void
     */
    public function testClassify() {
        $this->assertEquals(Core_Inflector::classify('artists_genres'), 'ArtistsGenre');
        $this->assertEquals(Core_Inflector::classify('file_systems'), 'FileSystem');
        $this->assertEquals(Core_Inflector::classify('news'), 'News');
    }

    /**
     * testTableNaming method
     *
     * @return void
     */
    public function testTabelize() {
        $this->assertEquals(Core_Inflector::tableize('ArtistsGenre'), 'artists_genres');
        $this->assertEquals(Core_Inflector::tableize('FileSystem'), 'file_systems');
        $this->assertEquals(Core_Inflector::tableize('News'), 'news');
    }

    /**
     * testHumanization method
     *
     * @return void
     */
    public function testHumanize() {
        $this->assertEquals(Core_Inflector::humanize('posts'), 'Posts');
        $this->assertEquals(Core_Inflector::humanize('posts_tags'), 'Posts Tags');
        $this->assertEquals(Core_Inflector::humanize('file_systems'), 'File Systems');
        $this->assertEquals(Core_Inflector::humanize('the-post-title', '-'), 'The Post Title');
    }

    /**
     * Tests adding transliterated characters to the map used in `Core_Inflector::slug()`.
     *
     * @return void
     */
    public function testAddTransliterations() {
        $this->assertEquals(Core_Inflector::slug('Montréal'), 'Montreal');
        $this->assertNotEquals(Core_Inflector::slug('Écaussines'), 'Ecaussines');

        Core_Inflector::rules('transliteration', array('/É|Ê/' => 'E'));
        $this->assertEquals(Core_Inflector::slug('Écaussines-d\'Enghien'), 'Ecaussines-d-Enghien');

        $this->assertNotEquals(Core_Inflector::slug('JØRGEN'), 'JORGEN');
        Core_Inflector::rules('transliteration', array('/Ø/' => 'O'));
        $this->assertEquals(Core_Inflector::slug('JØRGEN'), 'JORGEN');

        $this->assertNotEquals(Core_Inflector::slug('ÎÍ'), 'II');
        Core_Inflector::rules('transliteration', array('/Î|Í/' => 'I'));
        $this->assertEquals(Core_Inflector::slug('ÎÍ'), 'II');

        $this->assertEquals(Core_Inflector::slug('ABc'), 'ABc');
        Core_Inflector::rules('transliteration', array('AB' => 'a'));
        $this->assertEquals(Core_Inflector::slug('ABc'), 'aac');
    }

    public function testAddingUninflectedWords() {
        $this->assertEquals(Core_Inflector::pluralize('bord'), 'bords');
        Core_Inflector::rules('uninflected', 'bord');
        $this->assertEquals(Core_Inflector::pluralize('bord'), 'bord');
    }

    /**
     * Tests the storage mechanism for `$_underscored`, `$_camelized`,
     *  `$_humanized` and `$_pluralized`.
     *
     * @return void
     */
    /*
    public function testStorageMechanism() {
        Core_Inflector::reset();

        $expected = array('TestField' => 'test_field');
        $this->assertFalse($this->getProtectedValue('$_underscored'));
        $this->assertEquals(Core_Inflector::underscore('TestField'), 'test_field');
        $this->assertEquals($expected, $this->getProtectedValue('$_underscored'));
        $this->assertEquals(Core_Inflector::underscore('TestField'), 'test_field');

        $expected = array('test_field' => 'TestField');
        $this->assertFalse($this->getProtectedValue('$_camelized'));
        $this->assertEquals(Core_Inflector::camelize('test_field', true), 'TestField');
        $this->assertEquals($expected, $this->getProtectedValue('$_camelized'));
        $this->assertEquals(Core_Inflector::camelize('test_field', true), 'TestField');

        $expected = array('test_field:_' => 'Test Field');
        $this->assertFalse($this->getProtectedValue('$_humanized'));
        $this->assertEquals(Core_Inflector::humanize('test_field'), 'Test Field');
        $this->assertEquals($expected, $this->getProtectedValue('$_humanized'));
        $this->assertEquals(Core_Inflector::humanize('test_field'), 'Test Field');

        $expected = array('field' => 'fields');
        $this->assertFalse($this->getProtectedValue('$_pluralized'));
        $this->assertEquals(Core_Inflector::pluralize('field'), 'fields');
        $this->assertEquals($expected, $this->getProtectedValue('$_pluralized'));
        $this->assertEquals(Core_Inflector::pluralize('field'), 'fields');
    }
    */

    /**
     * This is a helper method for testStorageMechanism to fetch a private
     * property of the Core_Inflector class.
     *
     * @param string $property
     * @return string The value of the property.
     */
    /*
    private function getProtectedValue($property) {
            $info = Inspector::info("lithium\util\Core_Inflector::{$property}");
            return $info['value'];
    }
    */

}

?>