<?php

require_once 'C:\Users\Galuh Utama\workspace\Super-Simple-Framework\libs\core\Core_Config.php';
require_once 'C:\Users\Galuh Utama\workspace\Super-Simple-Framework\libs\core\exceptions.php';

/**
 * Test class for Config.
 * Generated by PHPUnit on 2012-01-28 at 00:17:40.
 */
class Core_ConfigTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Core_Config;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testSet()
    {
        Core_Config::set("hello.world.long.key1.key2", "test");
        Core_Config::set("foo", "BAR");
        Core_Config::set("foo.bar", "BAZ");
        Core_Config::set("foo.bar.baz", "BLAH");
        Core_Config::set("baz", "BLAH");
        Core_Config::set("acme.foobar", array("foo", "bar"));
        Core_Config::set("long.long2.long3", "hello");
        Core_Config::set("long.long2", "hello2");
        Core_Config::set("long", "hello3");
        Core_Config::set("null.value", null);
        Core_Config::set("null", null);
    }

    public function testGet()
    {
        $this->assertEquals(Core_Config::get("hello.world.long.key1.key2"), "test");
        $this->assertEquals(Core_Config::get("foo"), "BAR");
        $this->assertEquals(Core_Config::get("foo.bar"), "BAZ");
        $this->assertEquals(Core_Config::get("foo.bar.baz"), "BLAH");
        $this->assertEquals(Core_Config::get("baz"), "BLAH");
        $this->assertEquals(Core_Config::get("acme.foobar"), array("foo", "bar"));
        $this->assertEquals(Core_Config::get("long.long2.long3"), "hello");
        $this->assertEquals(Core_Config::get("long.long2"), "hello2");
        $this->assertEquals(Core_Config::get("long"), "hello3");
        $this->assertEquals(Core_Config::get("null.value"), null);
        $this->assertEquals(Core_Config::get("null"), null);
        $this->assertNull(Core_Config::get("lorem.ipsum.dolor"));
        $this->assertNull(Core_Config::get("olo.lol"));
        $this->assertNull(Core_Config::get("123"));
    }

    /**
     * @expectedException InvalidConfigKeyException
     */
    public function testValidKey()
    {
        Core_Config::set("(", "foo");
    }

    /**
     * @expectedException InvalidConfigKeyException
     */
    public function testValidKey2()
    {
        Core_Config::set("hel\$lo.-ddd-", "foo");
    }
}
?>
