<?php

require_once 'C:\Users\Galuh Utama\workspace\Super-Simple-Framework\libs\core\RouteParser.php';

/**
 * Test class for RouteParser.
 * Generated by PHPUnit on 2012-01-28 at 00:02:31.
 */
class RouteParserTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RouteParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RouteParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testParseCustom().
     */
    public function testParseCustom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testParseParamsFromRoute().
     */
    public function testParseParamsFromRoute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
