<?php

use Core\Config as Config;
use Core\InvalidConfigKeyException as InvalidConfigKeyException;

Config::set("debug", true);

Config::set("default.controller", "Home");
Config::set("default.action", "index");

?>